@startuml
skinparam defaultFontName Helvetica
skinparam shadowing false

title IoT Healthcare - Component Diagram


cloud Heroku-Instance {
    package "Frontend" {
      [angularjs]
    }
    package "Backend" {
       [spring]
    }
    database "PostgreSQL" {
       [database]
    }
}

package "Raspberry" {
  [daemon]
}

component "SmartBand" {
}

angularjs -- spring: HTTP
spring -left- database : Persistence layer
daemon -- spring: HTTP
daemon -- SmartBand: <&bluetooth> bluetooth
@enduml